const OK = 200;
const CREATED = 201;
const ACCEPTED = 202;
const MOVED_PERMANENTLY = 301;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const NOT_IMPLEMENTED = 501;

export {
	NOT_IMPLEMENTED,
	INTERNAL_SERVER_ERROR,
	CREATED,
	OK,
	NOT_FOUND,
	MOVED_PERMANENTLY,
	BAD_REQUEST,
	ACCEPTED,
	UNAUTHORIZED
};
