const NOT_IMPLEMENTED = 501;
const INTERNAL_SERVER_ERROR = 500;
const CREATED = 201;
const MOVED_PERMANENTLY = 301;
const BAD_REQUEST = 400;
const OK = 200;
const NOT_FOUND = 404;

export {
	NOT_IMPLEMENTED,
	INTERNAL_SERVER_ERROR,
	CREATED,
	OK,
	NOT_FOUND,
	MOVED_PERMANENTLY,
	BAD_REQUEST
};
